//! Build-time BDD feature view generator.
//!
//! llman-sdd 0.5 keeps specs in native layered Gherkin: `规则:` blocks headed
//! by `@req:<id>` tags with nested `场景:`. The gherkin parser behind
//! rstest-bdd 0.6.0-beta3 only walks top-level scenarios and hard-fails on a
//! tag directly above the unrecognized `规则:` line (its zh-CN table only has
//! rule = ["Rule"]). The `#[scenario]` bindings under tests/bdd therefore
//! compile against a generated flat view: rule-nested scenarios are hoisted
//! to the top level carrying their rule's `@req` tag, and the binding paths
//! point at this view instead of the spec source.
//!
//! Specs stay the single source of truth — the view is regenerated on every
//! build under target/bdd-specs/ (gitignored) and hoisting is structural
//! only: scenario names and step lines are copied verbatim.

use std::fs;
use std::path::PathBuf;

const SPECS_DIR: &str = "llmanspec/specs";
const VIEW_DIR: &str = "target/bdd-specs";

fn main() {
    println!("cargo:rerun-if-changed={SPECS_DIR}");
    let manifest = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set for build scripts"),
    );
    let Ok(entries) = fs::read_dir(manifest.join(SPECS_DIR)) else {
        return; // no specs dir in this checkout — nothing to generate
    };
    let view_root = manifest.join(VIEW_DIR);
    if view_root.exists() {
        fs::remove_dir_all(&view_root).expect("clear stale bdd feature view");
    }

    let mut capabilities: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    capabilities.sort();
    for capability in capabilities {
        let Some(name) = capability.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let Ok(source) = fs::read_to_string(capability.join(format!("{name}.feature"))) else {
            continue;
        };
        let dest = view_root.join(name).join(format!("{name}.feature"));
        fs::create_dir_all(dest.parent().expect("view path has a parent"))
            .expect("create bdd feature view dir");
        fs::write(&dest, flatten(&source)).expect("write bdd feature view");
    }
}

/// Hoist rule-nested scenarios into a top-level scenario view.
///
/// Line-oriented on purpose: llman-sdd's structural gates pin the spec
/// layout, so a small state machine suffices and step text is never
/// rewritten. `# language:` must stay the first line — gherkin ignores the
/// language header when comments precede it.
fn flatten(source: &str) -> String {
    const NOTE: &str =
        "# Generated by build.rs from llmanspec/specs — do not edit; edit the spec source.";
    let mut out = String::new();
    let mut pending: Vec<&str> = Vec::new(); // tag lines buffered for the next block header
    let mut rule_tags: Vec<&str> = Vec::new(); // @req tags heading the open 规则 block
    let mut rule_open = false; // inside a 规则 body that has not emitted a scenario yet
    let mut in_scenario = false; // copying scenario body verbatim
    let mut in_docstring = false;
    let mut noted = false;

    for raw in source.lines() {
        let line = raw.trim();
        if in_docstring {
            out.push_str(raw);
            out.push('\n');
            if line.starts_with("\"\"\"") {
                in_docstring = false;
            }
            continue;
        }
        if line.starts_with("\"\"\"") {
            in_docstring = true;
            out.push_str(raw);
            out.push('\n');
            continue;
        }
        if line.starts_with('@') {
            pending.push(raw);
            in_scenario = false; // a tag after scenario content starts a new block
            continue;
        }
        let is_rule = line.starts_with("规则:") || line.starts_with("Rule:");
        let is_scenario = line.starts_with("场景:")
            || line.starts_with("场景大纲:")
            || line.starts_with("Scenario:")
            || line.starts_with("Scenario Outline:");
        let is_background = line.starts_with("背景:") || line.starts_with("Background:");
        let is_feature = line.starts_with("功能:") || line.starts_with("Feature:");
        if is_rule {
            rule_tags = std::mem::take(&mut pending);
            rule_open = true;
            in_scenario = false;
            continue; // 规则 line and its description are view-only noise
        }
        if is_scenario || is_background {
            for tag in rule_tags.drain(..) {
                out.push_str(tag);
                out.push('\n');
            }
            for tag in pending.drain(..) {
                out.push_str(tag);
                out.push('\n');
            }
            rule_open = false;
            in_scenario = true;
            out.push_str(raw);
            out.push('\n');
            continue;
        }
        if is_feature {
            for tag in pending.drain(..) {
                out.push_str(tag);
                out.push('\n');
            }
            out.push_str(raw);
            out.push('\n');
            continue;
        }
        if !line.is_empty() && !noted && line.starts_with("# language") {
            // keep the language header first, then stamp provenance below it
            out.push_str(raw);
            out.push('\n');
            out.push_str(NOTE);
            out.push('\n');
            noted = true;
            continue;
        }
        if in_scenario {
            out.push_str(raw);
            out.push('\n');
        } else if rule_open {
            // rule description free text — requirement prose, not executable
        } else {
            out.push_str(raw);
            out.push('\n');
        }
    }
    out
}
