[package]
name = "xylitol"
version = "0.0.0-dev"
edition = "2024"
license = "MIT"
repository = "https://github.com/straydragon/xylitol"
description = "xylitol (placeholder)"
readme = "README.md"
keywords = []
categories = []
resolver = "2"

[dependencies]

[profile.dev]
opt-level = 0
codegen-units = 256
debug = 2
incremental = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "z"
codegen-units = 1
lto = "thin"
strip = "symbols"
panic = "abort"
incremental = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
