# language: zh-CN
# generated by `llman sdd solidify` from spec.toon (test-hooks-wiring)
# migrated from tests/features/hooks-wiring.feature
# 分工：agent-hooks = 调度器机制；本文件 = Driver/XyHookBus 库缝接线
功能: test-hooks-wiring
  场景: session-start
    假如 注册了匹配 "session_start" 的 hook
    当 执行操作 "确保新会话"
    那么 hook 被调用且上下文含键 reason

  场景: model-select
    假如 注册了匹配 "model_select" 的 hook
    当 执行操作 "选择模型 fake"
    那么 hook 被调用且上下文含键 model

  场景: thinking-select
    假如 注册了匹配 "thinking_level_select" 的 hook
    当 执行操作 "设置思考级别 high"
    那么 hook 被调用且上下文含键 level

  场景: session-tree
    假如 注册了匹配 "session_tree" 的 hook
    当 执行操作 "打开会话树"
    那么 hook 被调用且上下文含键 kind

  场景: tree-cancel
    假如 注册了匹配 session_before_tree 的 hook 且返回 block 树被拒绝
    当 执行操作 "打开会话树"
    那么 操作失败原因包含 "树被拒绝"

  场景: session-shutdown
    假如 注册了匹配 "session_shutdown" 的 hook
    当 执行操作 "切换会话 target"
    那么 hook 被调用且上下文含键 reason

  场景: switch-cancel
    假如 注册了匹配 session_before_switch 的 hook 且返回 block 切换被拒绝
    当 执行操作 "切换会话 target"
    那么 操作失败原因包含 "切换被拒绝"

  场景: user-bash
    假如 注册了匹配 "user_bash" 的 hook
    当 执行操作 "执行 bash"
    那么 hook 被调用且上下文含键 command

  场景: user-bash-block
    假如 注册了匹配 user_bash 的 hook 且返回 block bash被拒绝
    当 执行操作 "执行 bash"
    那么 操作失败原因包含 "bash被拒绝"

  场景: unknown-op
    当 执行操作 "未登记操作"
    那么 操作失败原因包含 "未知操作"
