// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// This file is generated by Apache Fory compiler.

#[derive(::fory::ForyEnum, Debug, Clone, PartialEq, Eq, Hash, Default)]
#[repr(i32)]
pub enum Method {
    #[default]
    HostDescribe = 1,
    Prompt = 2,
    Abort = 3,
    GetState = 4,
    SetModel = 5,
    CycleModel = 6,
    GetAvailableModels = 7,
    SetThinkingLevel = 8,
    Bash = 9,
    Compact = 10,
    GetSessionStats = 11,
    ExportHtml = 12,
    ExportJsonl = 13,
    ImportJsonl = 14,
    SwitchSession = 15,
    Fork = 16,
    GetMessages = 17,
    EstimateContext = 18,
    GetCommands = 19,
    SessionTree = 20,
    TravelSessionTree = 21,
    AppendEntryLabel = 22,
    ListSessions = 23,
    LoadSessionEntries = 24,
    NewSession = 25,
    GetSessionName = 26,
    SetSessionName = 27,
    SetSessionNameFor = 28,
    DeleteSession = 29,
    Reload = 30,
    LoadedResources = 31,
    GetQueueStats = 32,
    Steer = 33,
    FollowUp = 34,
    ClearQueue = 35,
    Subscribe = 36,
    ApproveTool = 37,
    AnswerQuestion = 38,
    Quit = 39,
    ArmToolFreeze = 40,
    PersistTrust = 41,
}

#[derive(::fory::ForyEnum, Debug, Clone, PartialEq, Eq, Hash, Default)]
#[repr(i32)]
pub enum TodoStatus {
    #[default]
    Pending = 0,
    InProgress = 1,
    Completed = 2,
}

#[derive(::fory::ForyEnum, Debug, Clone, PartialEq, Eq, Hash, Default)]
#[repr(i32)]
pub enum SessionTreeKind {
    #[default]
    MessageHistory = 0,
    FileBrowser = 1,
}

// Type ID 918966100 is generated from xy.wire.v3.Event
#[derive(::fory::ForyUnion, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Event {
    #[fory(unknown)]
    Unknown(::fory::UnknownCase),
    #[fory(id = 1, default)]
    ErrorEvent(self::ErrorEvent),
    #[fory(id = 2)]
    TextDelta(self::TextDelta),
    #[fory(id = 3)]
    ThinkingDelta(self::ThinkingDelta),
    #[fory(id = 4)]
    ToolStart(self::ToolStart),
    #[fory(id = 5)]
    ToolEnd(self::ToolEnd),
    #[fory(id = 6)]
    AgentEnd(self::AgentEnd),
    #[fory(id = 7)]
    ModelSelect(self::ModelSelect),
    #[fory(id = 8)]
    CompactionStart(self::CompactionStart),
    #[fory(id = 9)]
    TurnStart(self::TurnStart),
    #[fory(id = 10)]
    TurnEnd(self::TurnEnd),
    #[fory(id = 11)]
    MessageStart(self::MessageStart),
    #[fory(id = 12)]
    MessageEnd(self::MessageEnd),
    #[fory(id = 13)]
    MessageUpdate(self::MessageUpdate),
    #[fory(id = 14)]
    ToolExecutionUpdate(self::ToolExecutionUpdate),
    #[fory(id = 15)]
    CompactionEnd(self::CompactionEnd),
    #[fory(id = 16)]
    ContextTokenSettlement(self::ContextTokenSettlement),
    #[fory(id = 17)]
    QueueUpdate(self::QueueUpdate),
    #[fory(id = 18)]
    TodoListSnapshot(self::TodoListSnapshot),
}

impl ::std::default::Default for Event {
    fn default() -> Self {
        Self::ErrorEvent(<self::ErrorEvent as ::std::default::Default>::default())
    }
}

impl Event {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Event, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1222831235 is generated from xy.wire.v3.Command
#[derive(::fory::ForyUnion, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Command {
    #[fory(unknown)]
    Unknown(::fory::UnknownCase),
    #[fory(id = 1, default)]
    Prompt(self::Prompt),
    #[fory(id = 2)]
    Abort(self::Abort),
    #[fory(id = 3)]
    GetState(self::GetState),
    #[fory(id = 4)]
    SetModel(self::SetModel),
    #[fory(id = 5)]
    CycleModel(self::CycleModel),
    #[fory(id = 6)]
    GetAvailableModels(self::GetAvailableModels),
    #[fory(id = 7)]
    SetThinkingLevel(self::SetThinkingLevel),
    #[fory(id = 8)]
    Bash(self::Bash),
    #[fory(id = 9)]
    Compact(self::Compact),
    #[fory(id = 10)]
    GetSessionStats(self::GetSessionStats),
    #[fory(id = 11)]
    ExportHtml(self::ExportHtml),
    #[fory(id = 12)]
    ExportJsonl(self::ExportJsonl),
    #[fory(id = 13)]
    ImportJsonl(self::ImportJsonl),
    #[fory(id = 14)]
    SwitchSession(self::SwitchSession),
    #[fory(id = 15)]
    Fork(self::Fork),
    #[fory(id = 16)]
    GetMessages(self::GetMessages),
    #[fory(id = 17)]
    EstimateContext(self::EstimateContext),
    #[fory(id = 18)]
    GetCommands(self::GetCommands),
    #[fory(id = 19)]
    SessionTreeCmd(self::SessionTreeCmd),
    #[fory(id = 20)]
    TravelSessionTree(self::TravelSessionTree),
    #[fory(id = 21)]
    AppendEntryLabel(self::AppendEntryLabel),
    #[fory(id = 22)]
    ListSessions(self::ListSessions),
    #[fory(id = 23)]
    LoadSessionEntries(self::LoadSessionEntries),
    #[fory(id = 24)]
    NewSession(self::NewSession),
    #[fory(id = 25)]
    GetSessionName(self::GetSessionName),
    #[fory(id = 26)]
    SetSessionName(self::SetSessionName),
    #[fory(id = 27)]
    SetSessionNameFor(self::SetSessionNameFor),
    #[fory(id = 28)]
    DeleteSession(self::DeleteSession),
    #[fory(id = 29)]
    Reload(self::Reload),
    #[fory(id = 30)]
    LoadedResources(self::LoadedResources),
    #[fory(id = 31)]
    GetQueueStats(self::GetQueueStats),
    #[fory(id = 32)]
    Steer(self::Steer),
    #[fory(id = 33)]
    FollowUp(self::FollowUp),
    #[fory(id = 34)]
    ClearQueue(self::ClearQueue),
    #[fory(id = 35)]
    Subscribe(self::Subscribe),
    #[fory(id = 36)]
    ApproveTool(self::ApproveTool),
    #[fory(id = 37)]
    AnswerQuestion(self::AnswerQuestion),
    #[fory(id = 38)]
    Quit(self::Quit),
}

impl ::std::default::Default for Command {
    fn default() -> Self {
        Self::Prompt(<self::Prompt as ::std::default::Default>::default())
    }
}

impl Command {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Command, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 955602358 is generated from xy.wire.v3.SessionEntry
#[derive(::fory::ForyUnion, Clone, Debug, PartialEq, Eq, Hash)]
pub enum SessionEntry {
    #[fory(unknown)]
    Unknown(::fory::UnknownCase),
    #[fory(id = 1, default)]
    SessionHeader(self::SessionHeader),
    #[fory(id = 2)]
    MessageEntry(self::MessageEntry),
    #[fory(id = 3)]
    CompactionEntry(self::CompactionEntry),
    #[fory(id = 4)]
    BranchSummaryEntry(self::BranchSummaryEntry),
    #[fory(id = 5)]
    ModelChangeEntry(self::ModelChangeEntry),
    #[fory(id = 6)]
    ThinkingLevelChangeEntry(self::ThinkingLevelChangeEntry),
    #[fory(id = 7)]
    CustomEntry(self::CustomEntry),
    #[fory(id = 8)]
    CustomMessageEntry(self::CustomMessageEntry),
    #[fory(id = 9)]
    LabelEntry(self::LabelEntry),
    #[fory(id = 10)]
    SessionInfoEntry(self::SessionInfoEntry),
}

impl ::std::default::Default for SessionEntry {
    fn default() -> Self {
        Self::SessionHeader(<self::SessionHeader as ::std::default::Default>::default())
    }
}

impl SessionEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SessionEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4163298159 is generated from xy.wire.v3.Request
#[derive(::fory::ForyUnion, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Request {
    #[fory(unknown)]
    Unknown(::fory::UnknownCase),
    #[fory(id = 1, default)]
    Command(self::Command),
    #[fory(id = 2)]
    Describe(self::Describe),
    #[fory(id = 3)]
    Raw(self::Raw),
}

impl ::std::default::Default for Request {
    fn default() -> Self {
        Self::Command(<self::Command as ::std::default::Default>::default())
    }
}

impl Request {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Request, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2807078852 is generated from xy.wire.v3.ResponsePayload
#[derive(::fory::ForyUnion, Debug)]
pub enum ResponsePayload {
    #[fory(unknown)]
    Unknown(::fory::UnknownCase),
    #[fory(id = 1, default)]
    DescribeResult(self::DescribeResult),
    #[fory(id = 2)]
    SubscribeResult(self::SubscribeResult),
    #[fory(id = 3)]
    MessagesResult(self::MessagesResult),
    #[fory(id = 4)]
    TreeResult(self::TreeResult),
    #[fory(id = 5)]
    TravelResult(self::TravelResult),
    #[fory(id = 6)]
    RawOk(self::RawOk),
}

impl ::std::default::Default for ResponsePayload {
    fn default() -> Self {
        Self::DescribeResult(<self::DescribeResult as ::std::default::Default>::default())
    }
}

impl ResponsePayload {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ResponsePayload, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4112315476 is generated from xy.wire.v3.Notification
#[derive(::fory::ForyUnion, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Notification {
    #[fory(unknown)]
    Unknown(::fory::UnknownCase),
    #[fory(id = 1, default)]
    Event(self::Event),
    #[fory(id = 2)]
    Subscribed(self::Subscribed),
    #[fory(id = 3)]
    ResyncRequired(self::ResyncRequired),
    #[fory(id = 4)]
    Resources(self::Resources),
    #[fory(id = 5)]
    ApprovalRequested(self::ApprovalRequested),
    #[fory(id = 6)]
    QuestionRequested(self::QuestionRequested),
    #[fory(id = 7)]
    BashOutput(self::BashOutput),
}

impl ::std::default::Default for Notification {
    fn default() -> Self {
        Self::Event(<self::Event as ::std::default::Default>::default())
    }
}

impl Notification {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Notification, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1778949947 is generated from xy.wire.v3.Frame
#[derive(::fory::ForyUnion, Debug)]
pub enum Frame {
    #[fory(unknown)]
    Unknown(::fory::UnknownCase),
    #[fory(id = 1, default)]
    ClientRequest(self::ClientRequest),
    #[fory(id = 2)]
    ServerResponse(self::ServerResponse),
    #[fory(id = 3)]
    ServerNotification(self::ServerNotification),
}

impl ::std::default::Default for Frame {
    fn default() -> Self {
        Self::ClientRequest(<self::ClientRequest as ::std::default::Default>::default())
    }
}

impl Frame {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Frame, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4006788638 is generated from xy.wire.v3.TodoItem
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct TodoItem {
    #[fory(id = 1)]
    pub id: ::std::string::String,
    #[fory(id = 2)]
    pub content: ::std::string::String,
    #[fory(id = 3)]
    pub status: TodoStatus,
}

impl TodoItem {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TodoItem, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4176394835 is generated from xy.wire.v3.TodoList
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct TodoList {
    #[fory(id = 1)]
    pub items: ::std::vec::Vec<TodoItem>,
}

impl TodoList {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TodoList, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2432238467 is generated from xy.wire.v3.ErrorEvent
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ErrorEvent {
    #[fory(id = 1)]
    pub kind: ::std::string::String,
    #[fory(id = 2)]
    pub message: ::std::string::String,
}

impl ErrorEvent {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ErrorEvent, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2205700084 is generated from xy.wire.v3.TextDelta
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct TextDelta {
    #[fory(id = 1)]
    pub text: ::std::string::String,
}

impl TextDelta {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TextDelta, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2852785587 is generated from xy.wire.v3.ThinkingDelta
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ThinkingDelta {
    #[fory(id = 1)]
    pub text: ::std::string::String,
}

impl ThinkingDelta {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ThinkingDelta, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 920590217 is generated from xy.wire.v3.ToolStart
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ToolStart {
    #[fory(id = 1)]
    pub id: ::std::string::String,
    #[fory(id = 2)]
    pub name: ::std::string::String,
    #[fory(id = 3)]
    pub args_json: ::std::string::String,
}

impl ToolStart {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ToolStart, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2269529776 is generated from xy.wire.v3.ToolEnd
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ToolEnd {
    #[fory(id = 1)]
    pub id: ::std::string::String,
    #[fory(id = 2)]
    pub name: ::std::string::String,
    #[fory(id = 3)]
    pub result: ::std::string::String,
    #[fory(id = 4)]
    pub is_error: bool,
}

impl ToolEnd {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ToolEnd, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3146821503 is generated from xy.wire.v3.AgentEnd
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct AgentEnd {
}

impl AgentEnd {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<AgentEnd, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 577664694 is generated from xy.wire.v3.ModelSelect
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ModelSelect {
    #[fory(id = 1)]
    pub provider: ::std::string::String,
    #[fory(id = 2)]
    pub model_id: ::std::string::String,
}

impl ModelSelect {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ModelSelect, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3623091565 is generated from xy.wire.v3.CompactionStart
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct CompactionStart {
    #[fory(id = 1)]
    pub reason: ::std::string::String,
}

impl CompactionStart {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<CompactionStart, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 510563311 is generated from xy.wire.v3.TurnStart
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct TurnStart {
    #[fory(id = 1)]
    pub turn_index: u32,
}

impl TurnStart {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TurnStart, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2978716078 is generated from xy.wire.v3.TurnEnd
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct TurnEnd {
    #[fory(id = 1)]
    pub turn_index: u32,
}

impl TurnEnd {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TurnEnd, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1252993037 is generated from xy.wire.v3.MessageStart
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct MessageStart {
    #[fory(id = 1)]
    pub role: ::std::string::String,
    #[fory(id = 2, nullable = true)]
    pub message_json: ::std::option::Option<::std::string::String>,
}

impl MessageStart {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<MessageStart, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2899416207 is generated from xy.wire.v3.MessageEnd
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct MessageEnd {
    #[fory(id = 1)]
    pub role: ::std::string::String,
    #[fory(id = 2, nullable = true)]
    pub message_json: ::std::option::Option<::std::string::String>,
}

impl MessageEnd {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<MessageEnd, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2577239134 is generated from xy.wire.v3.MessageUpdate
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct MessageUpdate {
    #[fory(id = 1)]
    pub text: ::std::string::String,
    #[fory(id = 2, nullable = true)]
    pub thinking: ::std::option::Option<::std::string::String>,
    #[fory(id = 3, nullable = true)]
    pub message_json: ::std::option::Option<::std::string::String>,
}

impl MessageUpdate {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<MessageUpdate, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4138906141 is generated from xy.wire.v3.ToolExecutionUpdate
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ToolExecutionUpdate {
    #[fory(id = 1)]
    pub id: ::std::string::String,
    #[fory(id = 2)]
    pub output: ::std::string::String,
}

impl ToolExecutionUpdate {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ToolExecutionUpdate, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2153057558 is generated from xy.wire.v3.CompactionEnd
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct CompactionEnd {
    #[fory(id = 1, nullable = true)]
    pub result: ::std::option::Option<::std::string::String>,
    #[fory(id = 2)]
    pub aborted: bool,
    #[fory(id = 3)]
    pub reason: ::std::string::String,
    #[fory(id = 4)]
    pub will_retry: bool,
    #[fory(id = 5, nullable = true)]
    pub error_message: ::std::option::Option<::std::string::String>,
    #[fory(id = 6, nullable = true)]
    pub summary: ::std::option::Option<::std::string::String>,
    #[fory(id = 7, nullable = true)]
    pub tokens_before: ::std::option::Option<u64>,
    #[fory(id = 8, nullable = true)]
    pub tokens_after: ::std::option::Option<u64>,
    #[fory(id = 9, nullable = true)]
    pub notice: ::std::option::Option<::std::string::String>,
}

impl CompactionEnd {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<CompactionEnd, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1268955008 is generated from xy.wire.v3.ContextTokenSettlement
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ContextTokenSettlement {
    #[fory(id = 1)]
    pub tokens: u64,
    #[fory(id = 2)]
    pub provenance: ::std::string::String,
    #[fory(id = 3)]
    pub usage_tokens: u64,
    #[fory(id = 4)]
    pub trailing_tokens: u64,
    #[fory(id = 5, nullable = true)]
    pub last_usage_index: ::std::option::Option<u64>,
    #[fory(id = 6)]
    pub reason: ::std::string::String,
    #[fory(id = 7)]
    pub generation: u64,
}

impl ContextTokenSettlement {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ContextTokenSettlement, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3171535835 is generated from xy.wire.v3.QueueUpdate
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct QueueUpdate {
    #[fory(id = 1)]
    pub steer_count: u64,
    #[fory(id = 2)]
    pub follow_up_count: u64,
}

impl QueueUpdate {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<QueueUpdate, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2620081790 is generated from xy.wire.v3.TodoListSnapshot
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct TodoListSnapshot {
    #[fory(id = 1, nullable = true)]
    pub list: ::std::option::Option<TodoList>,
}

impl TodoListSnapshot {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TodoListSnapshot, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2829170300 is generated from xy.wire.v3.Prompt
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Prompt {
    #[fory(id = 1)]
    pub message: ::std::string::String,
}

impl Prompt {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Prompt, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2289333051 is generated from xy.wire.v3.Abort
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Abort {
}

impl Abort {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Abort, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1394275298 is generated from xy.wire.v3.GetState
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct GetState {
}

impl GetState {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<GetState, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 853920672 is generated from xy.wire.v3.SetModel
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SetModel {
    #[fory(id = 1)]
    pub provider: ::std::string::String,
    #[fory(id = 2)]
    pub model_id: ::std::string::String,
}

impl SetModel {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SetModel, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2124865986 is generated from xy.wire.v3.CycleModel
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct CycleModel {
}

impl CycleModel {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<CycleModel, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3758978573 is generated from xy.wire.v3.GetAvailableModels
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct GetAvailableModels {
}

impl GetAvailableModels {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<GetAvailableModels, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4092421349 is generated from xy.wire.v3.SetThinkingLevel
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SetThinkingLevel {
    #[fory(id = 1)]
    pub level: ::std::string::String,
}

impl SetThinkingLevel {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SetThinkingLevel, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3284185897 is generated from xy.wire.v3.Bash
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Bash {
    #[fory(id = 1)]
    pub command: ::std::string::String,
    #[fory(id = 2)]
    pub exclude_from_context: bool,
}

impl Bash {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Bash, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1107738787 is generated from xy.wire.v3.Compact
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Compact {
    #[fory(id = 1, nullable = true)]
    pub instructions: ::std::option::Option<::std::string::String>,
}

impl Compact {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Compact, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 397196162 is generated from xy.wire.v3.GetSessionStats
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct GetSessionStats {
}

impl GetSessionStats {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<GetSessionStats, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4222062745 is generated from xy.wire.v3.ExportHtml
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ExportHtml {
    #[fory(id = 1, nullable = true)]
    pub output_path: ::std::option::Option<::std::string::String>,
}

impl ExportHtml {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ExportHtml, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1664834918 is generated from xy.wire.v3.ExportJsonl
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ExportJsonl {
    #[fory(id = 1, nullable = true)]
    pub output_path: ::std::option::Option<::std::string::String>,
}

impl ExportJsonl {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ExportJsonl, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2002269573 is generated from xy.wire.v3.ImportJsonl
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ImportJsonl {
    #[fory(id = 1)]
    pub input_path: ::std::string::String,
}

impl ImportJsonl {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ImportJsonl, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 207009789 is generated from xy.wire.v3.SwitchSession
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SwitchSession {
    #[fory(id = 1)]
    pub session_path: ::std::string::String,
}

impl SwitchSession {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SwitchSession, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1437042094 is generated from xy.wire.v3.Fork
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Fork {
    #[fory(id = 1)]
    pub entry_id: ::std::string::String,
    #[fory(id = 2, nullable = true)]
    pub position: ::std::option::Option<::std::string::String>,
}

impl Fork {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Fork, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3782130412 is generated from xy.wire.v3.GetMessages
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct GetMessages {
}

impl GetMessages {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<GetMessages, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4227528577 is generated from xy.wire.v3.EstimateContext
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct EstimateContext {
}

impl EstimateContext {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<EstimateContext, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1822433479 is generated from xy.wire.v3.GetCommands
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct GetCommands {
}

impl GetCommands {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<GetCommands, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3387011641 is generated from xy.wire.v3.SessionTreeCmd
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SessionTreeCmd {
    #[fory(id = 1)]
    pub kind: SessionTreeKind,
}

impl SessionTreeCmd {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SessionTreeCmd, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1659072470 is generated from xy.wire.v3.TravelSessionTree
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct TravelSessionTree {
    #[fory(id = 1)]
    pub kind: SessionTreeKind,
    #[fory(id = 2)]
    pub entry_id: ::std::string::String,
}

impl TravelSessionTree {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TravelSessionTree, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3959534726 is generated from xy.wire.v3.AppendEntryLabel
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct AppendEntryLabel {
    #[fory(id = 1)]
    pub target_id: ::std::string::String,
    #[fory(id = 2, nullable = true)]
    pub label: ::std::option::Option<::std::string::String>,
}

impl AppendEntryLabel {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<AppendEntryLabel, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4038031340 is generated from xy.wire.v3.ListSessions
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ListSessions {
}

impl ListSessions {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ListSessions, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2525715877 is generated from xy.wire.v3.LoadSessionEntries
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct LoadSessionEntries {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
}

impl LoadSessionEntries {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<LoadSessionEntries, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 632232215 is generated from xy.wire.v3.NewSession
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct NewSession {
}

impl NewSession {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<NewSession, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 731655542 is generated from xy.wire.v3.GetSessionName
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct GetSessionName {
}

impl GetSessionName {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<GetSessionName, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 362281366 is generated from xy.wire.v3.SetSessionName
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SetSessionName {
    #[fory(id = 1)]
    pub name: ::std::string::String,
}

impl SetSessionName {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SetSessionName, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2004773129 is generated from xy.wire.v3.SetSessionNameFor
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SetSessionNameFor {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
    #[fory(id = 2)]
    pub name: ::std::string::String,
}

impl SetSessionNameFor {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SetSessionNameFor, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 678487181 is generated from xy.wire.v3.DeleteSession
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct DeleteSession {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
}

impl DeleteSession {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<DeleteSession, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2937939923 is generated from xy.wire.v3.Reload
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Reload {
}

impl Reload {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Reload, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1762311345 is generated from xy.wire.v3.LoadedResources
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct LoadedResources {
}

impl LoadedResources {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<LoadedResources, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3642094144 is generated from xy.wire.v3.GetQueueStats
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct GetQueueStats {
}

impl GetQueueStats {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<GetQueueStats, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 47126011 is generated from xy.wire.v3.Steer
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Steer {
    #[fory(id = 1)]
    pub message: ::std::string::String,
}

impl Steer {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Steer, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4152907407 is generated from xy.wire.v3.FollowUp
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct FollowUp {
    #[fory(id = 1)]
    pub message: ::std::string::String,
}

impl FollowUp {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<FollowUp, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2119178208 is generated from xy.wire.v3.ClearQueue
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ClearQueue {
    #[fory(id = 1)]
    pub clear_steer: bool,
    #[fory(id = 2)]
    pub clear_follow_up: bool,
}

impl ClearQueue {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ClearQueue, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3620714042 is generated from xy.wire.v3.Subscribe
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Subscribe {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
    #[fory(id = 2)]
    pub last_seq: u64,
}

impl Subscribe {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Subscribe, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1787997033 is generated from xy.wire.v3.ApproveTool
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ApproveTool {
    #[fory(id = 1)]
    pub call_id: ::std::string::String,
    #[fory(id = 2)]
    pub approved: bool,
}

impl ApproveTool {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ApproveTool, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3701480321 is generated from xy.wire.v3.AnswerQuestion
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct AnswerQuestion {
    #[fory(id = 1)]
    pub call_id: ::std::string::String,
    #[fory(id = 2)]
    pub answer: ::std::string::String,
}

impl AnswerQuestion {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<AnswerQuestion, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1217282764 is generated from xy.wire.v3.Quit
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Quit {
}

impl Quit {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Quit, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1059469350 is generated from xy.wire.v3.EntryBase
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct EntryBase {
    #[fory(id = 1)]
    pub id: ::std::string::String,
    #[fory(id = 2, nullable = true)]
    pub parent_id: ::std::option::Option<::std::string::String>,
    #[fory(id = 3)]
    pub timestamp: u64,
}

impl EntryBase {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<EntryBase, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1319788547 is generated from xy.wire.v3.SessionHeader
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SessionHeader {
    #[fory(id = 1)]
    pub version: u32,
    #[fory(id = 2)]
    pub id: ::std::string::String,
    #[fory(id = 3)]
    pub timestamp: u64,
    #[fory(id = 4)]
    pub cwd: ::std::string::String,
    #[fory(id = 5, nullable = true)]
    pub parent_session: ::std::option::Option<::std::string::String>,
    #[fory(id = 6, nullable = true)]
    pub fork_at_entry_id: ::std::option::Option<::std::string::String>,
}

impl SessionHeader {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SessionHeader, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 890889628 is generated from xy.wire.v3.MessageEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct MessageEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2)]
    pub message_json: ::std::string::String,
}

impl MessageEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<MessageEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2350714606 is generated from xy.wire.v3.CompactionPolicySnapshot
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct CompactionPolicySnapshot {
    #[fory(id = 1, nullable = true)]
    pub context_window: ::std::option::Option<u64>,
    #[fory(id = 2, nullable = true)]
    pub reserve_tokens: ::std::option::Option<u64>,
    #[fory(id = 3, nullable = true)]
    pub keep_recent_tokens: ::std::option::Option<u64>,
    #[fory(id = 4, nullable = true)]
    pub estimator_version: ::std::option::Option<::std::string::String>,
    #[fory(id = 5, nullable = true)]
    pub status: ::std::option::Option<::std::string::String>,
}

impl CompactionPolicySnapshot {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<CompactionPolicySnapshot, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1383298697 is generated from xy.wire.v3.CompactionEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct CompactionEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2)]
    pub summary: ::std::string::String,
    #[fory(id = 3)]
    pub first_kept_entry_id: ::std::string::String,
    #[fory(id = 4)]
    pub tokens_before: u64,
    #[fory(id = 5, nullable = true)]
    pub details_json: ::std::option::Option<::std::string::String>,
    #[fory(id = 6, nullable = true)]
    pub from_hook: ::std::option::Option<bool>,
    #[fory(id = 7, nullable = true)]
    pub policy: ::std::option::Option<CompactionPolicySnapshot>,
}

impl CompactionEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<CompactionEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2089769108 is generated from xy.wire.v3.BranchSummaryEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct BranchSummaryEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2)]
    pub from_id: ::std::string::String,
    #[fory(id = 3)]
    pub summary: ::std::string::String,
    #[fory(id = 4, nullable = true)]
    pub details_json: ::std::option::Option<::std::string::String>,
    #[fory(id = 5, nullable = true)]
    pub from_hook: ::std::option::Option<bool>,
}

impl BranchSummaryEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<BranchSummaryEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2370590739 is generated from xy.wire.v3.ModelChangeEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ModelChangeEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2)]
    pub provider: ::std::string::String,
    #[fory(id = 3)]
    pub model_id: ::std::string::String,
}

impl ModelChangeEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ModelChangeEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3361862214 is generated from xy.wire.v3.ThinkingLevelChangeEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ThinkingLevelChangeEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2)]
    pub thinking_level: ::std::string::String,
}

impl ThinkingLevelChangeEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ThinkingLevelChangeEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3947920593 is generated from xy.wire.v3.CustomEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct CustomEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2)]
    pub custom_type: ::std::string::String,
    #[fory(id = 3)]
    pub data_json: ::std::string::String,
}

impl CustomEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<CustomEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4097261514 is generated from xy.wire.v3.CustomMessageEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct CustomMessageEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2)]
    pub custom_type: ::std::string::String,
    #[fory(id = 3)]
    pub content_json: ::std::string::String,
    #[fory(id = 4)]
    pub display: bool,
    #[fory(id = 5, nullable = true)]
    pub details_json: ::std::option::Option<::std::string::String>,
}

impl CustomMessageEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<CustomMessageEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 38029938 is generated from xy.wire.v3.LabelEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct LabelEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2)]
    pub target_id: ::std::string::String,
    #[fory(id = 3, nullable = true)]
    pub label: ::std::option::Option<::std::string::String>,
}

impl LabelEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<LabelEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1116983243 is generated from xy.wire.v3.SessionInfoEntry
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SessionInfoEntry {
    #[fory(id = 1, nullable = true)]
    pub base: ::std::option::Option<EntryBase>,
    #[fory(id = 2, nullable = true)]
    pub name: ::std::option::Option<::std::string::String>,
}

impl SessionInfoEntry {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SessionInfoEntry, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 793268054 is generated from xy.wire.v3.SessionTreeNode
#[derive(::fory::ForyStruct, Debug, Default)]
pub struct SessionTreeNode {
    #[fory(id = 1)]
    pub entry: SessionEntry,
    #[fory(id = 2)]
    pub children: ::std::vec::Vec<SessionTreeNode>,
    #[fory(id = 3, nullable = true)]
    pub label: ::std::option::Option<::std::string::String>,
}

impl SessionTreeNode {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SessionTreeNode, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3576115421 is generated from xy.wire.v3.SessionTreeTravel
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SessionTreeTravel {
    #[fory(id = 1)]
    pub kind: SessionTreeKind,
    #[fory(id = 2)]
    pub selected_id: ::std::string::String,
    #[fory(id = 3, nullable = true)]
    pub leaf_id: ::std::option::Option<::std::string::String>,
    #[fory(id = 4, nullable = true)]
    pub editor_text: ::std::option::Option<::std::string::String>,
}

impl SessionTreeTravel {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SessionTreeTravel, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3469566652 is generated from xy.wire.v3.RpcError
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct RpcError {
    #[fory(id = 1)]
    pub code: ::std::string::String,
    #[fory(id = 2)]
    pub details: ::std::string::String,
}

impl RpcError {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<RpcError, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 4279742181 is generated from xy.wire.v3.Describe
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Describe {
}

impl Describe {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Describe, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1163077900 is generated from xy.wire.v3.Raw
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Raw {
    #[fory(id = 1)]
    pub method: Method,
    #[fory(id = 2)]
    pub json: ::std::string::String,
}

impl Raw {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Raw, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2007673709 is generated from xy.wire.v3.ClientRequest
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ClientRequest {
    #[fory(id = 1)]
    pub rpc_id: u64,
    #[fory(id = 2)]
    pub request: Request,
    #[fory(id = 3, nullable = true)]
    pub writer_token: ::std::option::Option<::std::string::String>,
}

impl ClientRequest {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ClientRequest, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3959661579 is generated from xy.wire.v3.DescribeResult
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct DescribeResult {
    #[fory(id = 1)]
    pub protocol: u32,
    #[fory(id = 2)]
    pub formats: ::std::vec::Vec<::std::string::String>,
}

impl DescribeResult {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<DescribeResult, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 738465498 is generated from xy.wire.v3.SubscribeResult
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct SubscribeResult {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
    #[fory(id = 2)]
    pub seq: u64,
}

impl SubscribeResult {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<SubscribeResult, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 473572778 is generated from xy.wire.v3.MessagesResult
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct MessagesResult {
    #[fory(id = 1)]
    pub entries: ::std::vec::Vec<SessionEntry>,
}

impl MessagesResult {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<MessagesResult, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1224273275 is generated from xy.wire.v3.TreeResult
#[derive(::fory::ForyStruct, Debug, Default)]
pub struct TreeResult {
    #[fory(id = 1)]
    pub nodes: ::std::vec::Vec<SessionTreeNode>,
}

impl TreeResult {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TreeResult, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1221079602 is generated from xy.wire.v3.TravelResult
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct TravelResult {
    #[fory(id = 1)]
    pub kind: SessionTreeKind,
    #[fory(id = 2)]
    pub selected_id: ::std::string::String,
    #[fory(id = 3, nullable = true)]
    pub leaf_id: ::std::option::Option<::std::string::String>,
    #[fory(id = 4, nullable = true)]
    pub editor_text: ::std::option::Option<::std::string::String>,
}

impl TravelResult {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<TravelResult, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 2906991758 is generated from xy.wire.v3.RawOk
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct RawOk {
    #[fory(id = 1)]
    pub json: ::std::string::String,
}

impl RawOk {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<RawOk, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1797427249 is generated from xy.wire.v3.ServerResponse
#[derive(::fory::ForyStruct, Debug, Default)]
pub struct ServerResponse {
    #[fory(id = 1)]
    pub rpc_id: u64,
    #[fory(id = 2)]
    pub ok: bool,
    #[fory(id = 3, nullable = true)]
    pub error: ::std::option::Option<RpcError>,
    #[fory(id = 4, nullable = true)]
    pub payload: ::std::option::Option<ResponsePayload>,
    #[fory(id = 5, nullable = true)]
    pub writer_token: ::std::option::Option<::std::string::String>,
}

impl ServerResponse {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ServerResponse, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1569001054 is generated from xy.wire.v3.Subscribed
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Subscribed {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
    #[fory(id = 2)]
    pub seq: u64,
}

impl Subscribed {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Subscribed, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3720193907 is generated from xy.wire.v3.ResyncRequired
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ResyncRequired {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
}

impl ResyncRequired {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ResyncRequired, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1269773646 is generated from xy.wire.v3.Resources
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Resources {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
    #[fory(id = 2)]
    pub snapshot_json: ::std::string::String,
}

impl Resources {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<Resources, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 613025320 is generated from xy.wire.v3.ApprovalRequested
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ApprovalRequested {
    #[fory(id = 1)]
    pub call_id: ::std::string::String,
}

impl ApprovalRequested {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ApprovalRequested, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 3372618103 is generated from xy.wire.v3.QuestionRequested
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct QuestionRequested {
    #[fory(id = 1)]
    pub call_id: ::std::string::String,
}

impl QuestionRequested {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<QuestionRequested, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1876308991 is generated from xy.wire.v3.BashOutput
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct BashOutput {
    #[fory(id = 1)]
    pub session_id: ::std::string::String,
    #[fory(id = 2)]
    pub bash_id: ::std::string::String,
    #[fory(id = 3)]
    pub seq: u64,
    #[fory(id = 4)]
    pub data: ::std::string::String,
}

impl BashOutput {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<BashOutput, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

// Type ID 1395672812 is generated from xy.wire.v3.ServerNotification
#[derive(::fory::ForyStruct, Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct ServerNotification {
    #[fory(id = 1)]
    pub seq: u64,
    #[fory(id = 2)]
    pub notification: Notification,
}

impl ServerNotification {
    pub fn to_bytes(&self) -> ::std::result::Result<::std::vec::Vec<u8>, ::fory::Error> {
        let fory = detail::get_fory();
        fory.serialize(self)
    }

    pub fn from_bytes(data: &[u8]) -> ::std::result::Result<ServerNotification, ::fory::Error> {
        let fory = detail::get_fory();
        fory.deserialize(data)
    }
}

pub fn register_types(fory: &mut ::fory::Fory) -> ::std::result::Result<(), ::fory::Error> {
    fory.register::<Method>(60195926)?;
    fory.register::<TodoStatus>(1489694096)?;
    fory.register::<SessionTreeKind>(3393463021)?;
    fory.register_union::<Event>(918966100)?;
    fory.register_union::<Command>(1222831235)?;
    fory.register_union::<SessionEntry>(955602358)?;
    fory.register_union::<Request>(4163298159)?;
    fory.register_union::<ResponsePayload>(2807078852)?;
    fory.register_union::<Notification>(4112315476)?;
    fory.register_union::<Frame>(1778949947)?;
    fory.register::<TodoItem>(4006788638)?;
    fory.register::<TodoList>(4176394835)?;
    fory.register::<ErrorEvent>(2432238467)?;
    fory.register::<TextDelta>(2205700084)?;
    fory.register::<ThinkingDelta>(2852785587)?;
    fory.register::<ToolStart>(920590217)?;
    fory.register::<ToolEnd>(2269529776)?;
    fory.register::<AgentEnd>(3146821503)?;
    fory.register::<ModelSelect>(577664694)?;
    fory.register::<CompactionStart>(3623091565)?;
    fory.register::<TurnStart>(510563311)?;
    fory.register::<TurnEnd>(2978716078)?;
    fory.register::<MessageStart>(1252993037)?;
    fory.register::<MessageEnd>(2899416207)?;
    fory.register::<MessageUpdate>(2577239134)?;
    fory.register::<ToolExecutionUpdate>(4138906141)?;
    fory.register::<CompactionEnd>(2153057558)?;
    fory.register::<ContextTokenSettlement>(1268955008)?;
    fory.register::<QueueUpdate>(3171535835)?;
    fory.register::<TodoListSnapshot>(2620081790)?;
    fory.register::<Prompt>(2829170300)?;
    fory.register::<Abort>(2289333051)?;
    fory.register::<GetState>(1394275298)?;
    fory.register::<SetModel>(853920672)?;
    fory.register::<CycleModel>(2124865986)?;
    fory.register::<GetAvailableModels>(3758978573)?;
    fory.register::<SetThinkingLevel>(4092421349)?;
    fory.register::<Bash>(3284185897)?;
    fory.register::<Compact>(1107738787)?;
    fory.register::<GetSessionStats>(397196162)?;
    fory.register::<ExportHtml>(4222062745)?;
    fory.register::<ExportJsonl>(1664834918)?;
    fory.register::<ImportJsonl>(2002269573)?;
    fory.register::<SwitchSession>(207009789)?;
    fory.register::<Fork>(1437042094)?;
    fory.register::<GetMessages>(3782130412)?;
    fory.register::<EstimateContext>(4227528577)?;
    fory.register::<GetCommands>(1822433479)?;
    fory.register::<SessionTreeCmd>(3387011641)?;
    fory.register::<TravelSessionTree>(1659072470)?;
    fory.register::<AppendEntryLabel>(3959534726)?;
    fory.register::<ListSessions>(4038031340)?;
    fory.register::<LoadSessionEntries>(2525715877)?;
    fory.register::<NewSession>(632232215)?;
    fory.register::<GetSessionName>(731655542)?;
    fory.register::<SetSessionName>(362281366)?;
    fory.register::<SetSessionNameFor>(2004773129)?;
    fory.register::<DeleteSession>(678487181)?;
    fory.register::<Reload>(2937939923)?;
    fory.register::<LoadedResources>(1762311345)?;
    fory.register::<GetQueueStats>(3642094144)?;
    fory.register::<Steer>(47126011)?;
    fory.register::<FollowUp>(4152907407)?;
    fory.register::<ClearQueue>(2119178208)?;
    fory.register::<Subscribe>(3620714042)?;
    fory.register::<ApproveTool>(1787997033)?;
    fory.register::<AnswerQuestion>(3701480321)?;
    fory.register::<Quit>(1217282764)?;
    fory.register::<EntryBase>(1059469350)?;
    fory.register::<SessionHeader>(1319788547)?;
    fory.register::<MessageEntry>(890889628)?;
    fory.register::<CompactionPolicySnapshot>(2350714606)?;
    fory.register::<CompactionEntry>(1383298697)?;
    fory.register::<BranchSummaryEntry>(2089769108)?;
    fory.register::<ModelChangeEntry>(2370590739)?;
    fory.register::<ThinkingLevelChangeEntry>(3361862214)?;
    fory.register::<CustomEntry>(3947920593)?;
    fory.register::<CustomMessageEntry>(4097261514)?;
    fory.register::<LabelEntry>(38029938)?;
    fory.register::<SessionInfoEntry>(1116983243)?;
    fory.register::<SessionTreeNode>(793268054)?;
    fory.register::<SessionTreeTravel>(3576115421)?;
    fory.register::<RpcError>(3469566652)?;
    fory.register::<Describe>(4279742181)?;
    fory.register::<Raw>(1163077900)?;
    fory.register::<ClientRequest>(2007673709)?;
    fory.register::<DescribeResult>(3959661579)?;
    fory.register::<SubscribeResult>(738465498)?;
    fory.register::<MessagesResult>(473572778)?;
    fory.register::<TreeResult>(1224273275)?;
    fory.register::<TravelResult>(1221079602)?;
    fory.register::<RawOk>(2906991758)?;
    fory.register::<ServerResponse>(1797427249)?;
    fory.register::<Subscribed>(1569001054)?;
    fory.register::<ResyncRequired>(3720193907)?;
    fory.register::<Resources>(1269773646)?;
    fory.register::<ApprovalRequested>(613025320)?;
    fory.register::<QuestionRequested>(3372618103)?;
    fory.register::<BashOutput>(1876308991)?;
    fory.register::<ServerNotification>(1395672812)?;
    ::std::result::Result::Ok(())
}

mod detail {
    use super::*;

    pub(super) fn get_fory() -> &'static ::fory::Fory {
        static FORY: ::std::sync::OnceLock<::fory::Fory> = ::std::sync::OnceLock::new();
        FORY.get_or_init(|| {
            let mut fory = ::fory::Fory::builder()
                .xlang(true)
                .track_ref(true)
                .compatible(true)
                .build();
            register_types(&mut fory).expect("failed to register fory types");
            fory
        })
    }
}
