# language: zh-CN
# generated by `llman sdd solidify` from spec.toon (agent-runtime)
功能: agent-runtime
  场景: react-terminates
    假如 mock 模型先 tool 后无 tool
    当 运行 AgentRuntime
    那么 先执行工具再结束且无 adk 类型

  场景: stream-is-xyevent
    假如 消费事件流
    当 轮询
    那么 每项为 XyEvent

  场景: continues-after-tools
    假如 mock 模型先 tool 后无 tool
    当 运行 AgentRuntime
    那么 turn_end 事件包含 toolResult

  场景: done-not-turn-end
    假如 mock 模型先 tool 后无 tool
    当 运行 AgentRuntime
    那么 turn_end 事件包含 toolResult

  场景: abort-drops-sse
    假如 已装配慢速流式 mock 模型
    当 经 Driver 启动会话并在首个 TextDelta 后 abort
    那么 事件流包含 aborted 错误

  场景: builder-build
    假如 AgentBuilder 已装配依赖
    当 build
    那么 得到 AgentRuntime

  场景: ports-exist
    假如 检查 runtime_protocol 端口
    当 SessionStore 与 EventSink
    那么 trait 存在且可被实现

  场景: steer-before-model
    假如 装配并运行入队 steer 的 agent
    当 检查队列与历史
    那么 steer 计数归零且已处理

  场景: followup-extends
    假如 装配无工具 agent 并入队 follow_up
    当 运行至将结束
    那么 继续循环而非 AgentEnd

  场景: queue-update
    假如 装配 agent 并入队 steer
    当 观察事件流
    那么 出现 QueueUpdate 且计数正确

  场景: abort-clears-steer
    假如 装配 agent 并入队 steer 与 follow_up
    当 abort
    那么 steer 空且 follow_up 保留

  场景: second-run-after-abort
    假如 装配慢速 agent 并在首轮 abort 后
    当 再次运行
    那么 正常完成而非立即 aborted

  场景: unknown-ok
    假如 构造内部专用 XyEvent 变体
    当 经 to_wire_event 降级
    那么 返回 None 且不 panic

  场景: default-thinking
    假如 装配未设 thinking 的 agent
    当 查询 thinking level
    那么 返回默认值

  场景: cwd-missing
    假如 会话记录 cwd 指向不存在路径
    当 调用 load_validated
    那么 错误含路径

  场景: roundtrip
    假如 构造 XyEvent TextDelta
    当 经 protocol 往返
    那么 字段保留

  场景: abort-cancels-bang
    假如 启动交互 bang 长命令后 abort
    当 检查 bash 结果
    那么 cancelled 为 true

  场景: no-facade
    假如 检查 agent/facade.rs
    当 不存在该模块
    那么 facade 保持移除

  场景: no-rloop
    假如 在 src 中搜索 loop raw identifier
    当 运行检查
    那么 零匹配

  场景: before-denies
    假如 注册匹配 bash 的 before 拒绝 hook
    当 运行 AgentRuntime 触发 bash
    那么 tool-error 回写且未执行
