#!/usr/bin/env python3
"""Generate playground tokens from DESIGN.md frontmatter.

SSOT: src/app/tui/DESIGN.md → colors.* (dark) + colors_light.* (light)
Writes: tokens.css, tokens.js (same directory as this script).

Usage (from repo root or any cwd):
  python3 src/app/tui/design/playground/sync_tokens.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DESIGN = HERE.parent.parent / "DESIGN.md"


def parse_color_block(fm: str, key: str) -> list[tuple[str, str]]:
    block = re.search(rf"^{key}:\n(.*?)(?=^[a-z_]+:|\Z)", fm, re.S | re.M)
    if not block:
        raise SystemExit(f"DESIGN.md: missing {key}: block")
    pairs = re.findall(
        r"^\s+([a-z0-9-]+):\s*\"?(#[0-9a-fA-F]{6})\"?",
        block.group(1),
        re.M,
    )
    if not pairs:
        raise SystemExit(f"DESIGN.md: no color tokens in {key}")
    return [(n, h.lower()) for n, h in pairs]


def parse_schemes(text: str) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    m = re.search(r"^---\n(.*?)\n---", text, re.S | re.M)
    if not m:
        raise SystemExit("DESIGN.md: missing YAML frontmatter")
    fm = m.group(1)
    dark = parse_color_block(fm, "colors")
    light = parse_color_block(fm, "colors_light")
    dark_names = [n for n, _ in dark]
    light_names = [n for n, _ in light]
    if dark_names != light_names:
        raise SystemExit(
            "DESIGN.md: colors / colors_light keys must match "
            f"(dark={dark_names!r} light={light_names!r})"
        )
    return dark, light


def scheme_css_block(selector: str, colors: list[tuple[str, str]]) -> list[str]:
    lines = [f"{selector} {{"]
    for name, hex_ in colors:
        lines.append(f"  --{name}: {hex_};")
    lines += [
        "",
        "  /* page chrome: aliases of DESIGN tokens only */",
        "  --page-bg: var(--surface);",
        "  --page-fg: var(--on-surface);",
        "  --hairline: var(--tool-pending-bg);",
        '  --mono: ui-monospace, "Cascadia Code", "SF Mono", Menlo, Consolas, monospace;',
        "}",
        "",
    ]
    return lines


def write_css(
    dark: list[tuple[str, str]], light: list[tuple[str, str]]
) -> str:
    lines = [
        "/* AUTO-GENERATED by sync_tokens.py — do not edit by hand.",
        " * SSOT: src/app/tui/DESIGN.md colors + colors_light.",
        " * Re-run: python3 src/app/tui/design/playground/sync_tokens.py",
        " */",
    ]
    lines += scheme_css_block(":root, [data-scheme=\"dark\"]", dark)
    lines += scheme_css_block("[data-scheme=\"light\"]", light)
    return "\n".join(lines)


def write_js(
    dark: list[tuple[str, str]], light: list[tuple[str, str]]
) -> str:
    def items(colors: list[tuple[str, str]]) -> str:
        return ",\n".join(f'  ["{n}", "{h}"]' for n, h in colors)

    return (
        "/* AUTO-GENERATED by sync_tokens.py — do not edit by hand. */\n"
        "window.DESIGN_COLORS = {\n"
        "  dark: [\n"
        f"{items(dark)}\n"
        "  ],\n"
        "  light: [\n"
        f"{items(light)}\n"
        "  ],\n"
        "};\n"
        "// Back-compat: default swatches = dark MVP.\n"
        "window.DESIGN_COLORS_FLAT = window.DESIGN_COLORS.dark;\n"
    )


def main() -> int:
    if not DESIGN.is_file():
        print(f"error: DESIGN.md not found at {DESIGN}", file=sys.stderr)
        return 1
    dark, light = parse_schemes(DESIGN.read_text(encoding="utf-8"))
    css_path = HERE / "tokens.css"
    js_path = HERE / "tokens.js"
    css_path.write_text(write_css(dark, light), encoding="utf-8")
    js_path.write_text(write_js(dark, light), encoding="utf-8")
    print(f"wrote {css_path} ({len(dark)} dark + {len(light)} light)")
    print(f"wrote {js_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
