#!/usr/bin/env python3
"""Generate playground tokens from DESIGN.md frontmatter.

SSOT: src/app/tui/DESIGN.md → colors.*
Writes: tokens.css, tokens.js (same directory as this script).

Usage (from repo root or any cwd):
  python3 src/app/tui/design/playground/sync_tokens.py

Verify: change colors.accent in DESIGN.md, re-run, refresh index.html.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DESIGN = HERE.parent.parent / "DESIGN.md"


def parse_colors(text: str) -> list[tuple[str, str]]:
    m = re.search(r"^---\n(.*?)\n---", text, re.S | re.M)
    if not m:
        raise SystemExit("DESIGN.md: missing YAML frontmatter")
    fm = m.group(1)
    block = re.search(r"^colors:\n(.*?)(?=^[a-z]+:|\Z)", fm, re.S | re.M)
    if not block:
        raise SystemExit("DESIGN.md: missing colors: block")
    pairs = re.findall(
        r"^\s+([a-z0-9-]+):\s*\"?(#[0-9a-fA-F]{6})\"?",
        block.group(1),
        re.M,
    )
    if not pairs:
        raise SystemExit("DESIGN.md: no color tokens found")
    return [(n, h.lower()) for n, h in pairs]


def write_css(colors: list[tuple[str, str]]) -> str:
    lines = [
        "/* AUTO-GENERATED by sync_tokens.py — do not edit by hand.",
        " * SSOT: src/app/tui/DESIGN.md frontmatter colors.",
        " * Re-run: python3 src/app/tui/design/playground/sync_tokens.py",
        " */",
        ":root {",
    ]
    for name, hex_ in colors:
        lines.append(f"  --{name}: {hex_};")
    lines += [
        "",
        "  /* page chrome: aliases of DESIGN tokens only */",
        "  --page-bg: var(--surface);",
        "  --page-fg: var(--on-surface);",
        "  --hairline: var(--tool-pending-bg);",
        '  --mono: ui-monospace, "Cascadia Code", "SF Mono", Menlo, Consolas, monospace;',
        "}",
        "",
    ]
    return "\n".join(lines)


def write_js(colors: list[tuple[str, str]]) -> str:
    items = ",\n".join(f'  ["{n}", "{h}"]' for n, h in colors)
    return (
        "/* AUTO-GENERATED by sync_tokens.py — do not edit by hand. */\n"
        "window.DESIGN_COLORS = [\n"
        f"{items}\n"
        "];\n"
    )


def main() -> int:
    if not DESIGN.is_file():
        print(f"error: DESIGN.md not found at {DESIGN}", file=sys.stderr)
        return 1
    colors = parse_colors(DESIGN.read_text(encoding="utf-8"))
    css_path = HERE / "tokens.css"
    js_path = HERE / "tokens.js"
    css_path.write_text(write_css(colors), encoding="utf-8")
    js_path.write_text(write_js(colors), encoding="utf-8")
    print(f"wrote {css_path} ({len(colors)} colors)")
    print(f"wrote {js_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
