/* AUTO-GENERATED by sync_tokens.py — do not edit by hand. */
window.DESIGN_COLORS = [
  ["on-surface", "#cdd6f4"],
  ["muted", "#6c7086"],
  ["accent", "#89b4fa"],
  ["user", "#cba6f7"],
  ["assistant", "#cdd6f4"],
  ["tool", "#6c7086"],
  ["error", "#f38ba8"],
  ["warning", "#f9e2af"],
  ["success", "#a6e3a1"],
  ["diff-added", "#a6e3a1"],
  ["diff-removed", "#f38ba8"],
  ["diff-context", "#6c7086"],
  ["diff-added-bg", "#1e2b22"],
  ["diff-removed-bg", "#2b1e24"],
  ["diff-added-word-bg", "#2d4a35"],
  ["diff-removed-word-bg", "#4a2d35"],
  ["surface", "#1e1e2e"],
  ["tool-pending-bg", "#313244"],
  ["tool-success-bg", "#24352a"],
  ["tool-error-bg", "#352428"],
  ["user-message-bg", "#313244"]
];
