//! specta TypeScript export for the product envelope + method table.

use specta::Types;
use specta_typescript::Typescript;

use super::command::Command;
use super::envelope::{
    ApprovalRequestedPayload, HostDescribeValue, HostHelloPayload, PROTOCOL_VERSION,
    QuestionRequestedPayload, RpcError, RpcMessage, RpcResult, SessionEventPayload,
    SessionResyncRequiredPayload, SessionSubscribedPayload,
};
use super::event::Event;
use super::method::{DOWNLINK_METHODS, UNARY_METHODS};

/// Header written above the generated TypeScript.
pub const BINDINGS_HEADER: &str = "\
// Generated by `just gen-protocol-ts`. DO NOT EDIT.
// Product envelope + method-table payloads. OpenAPI is not the type SSOT.
";

/// Relative path from the crate root (checked in).
pub const BINDINGS_RELATIVE_PATH: &str = "clients/typescript/bindings.ts";

/// Register the specta graph required by the product type gate.
pub fn protocol_types() -> Types {
    Types::default()
        .register::<RpcMessage>()
        .register::<RpcResult>()
        .register::<RpcError>()
        .register::<SessionEventPayload>()
        .register::<SessionSubscribedPayload>()
        .register::<SessionResyncRequiredPayload>()
        .register::<HostHelloPayload>()
        .register::<ApprovalRequestedPayload>()
        .register::<QuestionRequestedPayload>()
        .register::<HostDescribeValue>()
        .register::<Event>()
        .register::<Command>()
}

fn ts_const_string_array(name: &str, type_name: &str, items: &[&str]) -> String {
    let mut out = format!("export const {name} = [\n");
    for item in items {
        out.push_str("  \"");
        out.push_str(item);
        out.push_str("\",\n");
    }
    out.push_str("] as const;\n");
    out.push_str("export type ");
    out.push_str(type_name);
    out.push_str(" = typeof ");
    out.push_str(name);
    out.push_str("[number];\n");
    out
}

/// Render checked-in TypeScript bindings (envelope types + method-name tables).
pub fn export_typescript_bindings() -> Result<String, String> {
    let types = protocol_types();
    let mut body = Typescript::default()
        .header(BINDINGS_HEADER)
        .export(&types, specta_serde::Format)
        .map_err(|e| e.to_string())?;
    if !body.ends_with('\n') {
        body.push('\n');
    }
    body.push('\n');
    body.push_str(&format!(
        "export const PROTOCOL_VERSION = {PROTOCOL_VERSION} as const;\n"
    ));
    body.push_str(&ts_const_string_array(
        "UNARY_METHODS",
        "UnaryMethod",
        UNARY_METHODS,
    ));
    body.push_str(&ts_const_string_array(
        "DOWNLINK_METHODS",
        "DownlinkMethod",
        DOWNLINK_METHODS,
    ));
    Ok(strip_trailing_whitespace(&body))
}

fn strip_trailing_whitespace(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    for line in src.split_inclusive('\n') {
        match line.strip_suffix('\n') {
            Some(content) => {
                out.push_str(content.trim_end());
                out.push('\n');
            }
            None => out.push_str(line.trim_end()),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_in_bindings_match_export() {
        let generated = export_typescript_bindings().expect("specta export");
        let checked = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/clients/typescript/bindings.ts"
        ));
        assert_eq!(
            generated, checked,
            "stale bindings; run `just gen-protocol-ts`"
        );
    }

    #[test]
    fn export_contains_envelope_and_method_table() {
        let ts = export_typescript_bindings().expect("specta export");
        assert!(
            ts.contains("client-request"),
            "kebab-case envelope tag missing:\n{ts}"
        );
        assert!(ts.contains("rpcId"), "rpcId rename missing:\n{ts}");
        assert!(ts.contains("text_delta"), "Event snake_case missing:\n{ts}");
        assert!(ts.contains("\"prompt\""));
        assert!(ts.contains("\"host.describe\""));
        assert!(ts.contains("\"session/event\""));
        assert!(ts.contains("UNARY_METHODS"));
        assert!(ts.contains("PROTOCOL_VERSION"));
        assert!(!ts.contains("openapi"), "OpenAPI must not be the SSOT");
    }
}
