#!/usr/bin/env python3
"""Generate designing/generated/AGENT-INDEX.md from designing/*/modules.

Usage:
  python3 scripts/gen_designing_index.py
  python3 scripts/gen_designing_index.py --stdout
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DESIGNING = REPO / "designing"
INDEX = DESIGNING / "generated" / "AGENT-INDEX.md"


def module_summary(intent: Path) -> str:
    for raw in intent.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith(">"):
            continue
        return line
    return ""


def iter_modules() -> list[tuple[str, Path]]:
    rows: list[tuple[str, Path]] = []
    if not DESIGNING.is_dir():
        return rows
    for surface in sorted(p for p in DESIGNING.iterdir() if p.is_dir()):
        mods = surface / "modules"
        if not mods.is_dir():
            continue
        for path in sorted(p for p in mods.iterdir() if p.is_dir()):
            rows.append((surface.name, path))
    return rows


def render_index() -> str:
    lines: list[str] = []
    for surface, path in iter_modules():
        intent = path / "intent.md"
        states_dir = path / "states"
        states = (
            sorted(p.stem for p in states_dir.glob("*.yaml"))
            if states_dir.is_dir()
            else []
        )
        summary = module_summary(intent) if intent.is_file() else "(missing intent.md)"
        lines.append(
            f"| {surface} | {path.name} | {summary} | {', '.join(states) or '—'} | `/{surface}/{path.name}` |"
        )
    body = "\n".join(lines) if lines else "| — | — | (no modules) | — | — |"
    return (
        "<!-- AUTO-GENERATED by scripts/gen_designing_index.py — do not edit. -->\n"
        "# designing AGENT-INDEX\n\n"
        "Agent 改某表面：先读**产品代码**，再读短 `intent.md` + `states/*.yaml`。"
        "禁止把 `app/` 或整包 HTML 当默认上下文。无独立快捷键模块。"
        "预览 endpoint：`/{surface}/{id}/{state}`（例 `/tui/diff/side-by-side`）。\n"
        "`tui-lab` 面是**实验原型区**（未接入产品）；晋级 / 淘汰流程见 `designing/AGENTS.md`。\n\n"
        "| surface | id | 一句话 | states | endpoint |\n"
        "|---|---|---|---|---|\n"
        f"{body}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print instead of write")
    args = ap.parse_args()
    text = render_index()
    if args.stdout:
        sys.stdout.write(text)
        return 0
    INDEX.parent.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(text, encoding="utf-8")
    print(f"wrote {INDEX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
