#!/usr/bin/env python3
"""Generate configs/testing/live-provider.example.yaml (maintenance, not in qa).

The repo only ships auto-generated examples: the live-provider example is the
single source for what a user copies to <global-dir>/dev/live-provider.yaml
(global dir = $XYLITOL_CONFIG_DIR, else $XDG_CONFIG_HOME/xylitol, else
~/.config/xylitol — shared across machines via the dotxylitol repo).

Fields MUST stay aligned with `LiveProviderFile` in
packages/xylitol-ai-bridge/tests/lab_responses_prompt_cache.rs:
enabled / base_url / model / api_key / max_output_tokens / serial.

Usage:
  python3 scripts/gen_live_provider_example.py
  just gen-live-provider-example
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TARGET = REPO_ROOT / "configs" / "testing" / "live-provider.example.yaml"

TEMPLATE = """\
# Dedicated live-provider integration config (Responses prompt-cache counterexample).
# Auto-generated by scripts/gen_live_provider_example.py — edit the template there.
#
# Place at <global-dir>/dev/live-provider.yaml and set `enabled: true`.
# Global dir resolution: $XYLITOL_CONFIG_DIR → $XDG_CONFIG_HOME/xylitol →
# ~/.config/xylitol (shared across machines via the dotxylitol repo).
# `just qa` runs the suite strictly serially AFTER workspace nextest; when
# `enabled` is false or the file is missing, the step skips (pass).
#
# Env overrides (optional):
#   XYLITOL_LIVE_PROVIDER_CONFIG=/path/to.yaml
#   XYLITOL_LIVE_PROVIDER=1|0          # force enable/disable
#   XYLITOL_LIVE_BASE_URL / XYLITOL_LIVE_MODEL / XYLITOL_LIVE_API_KEY
#   XYLITOL_LIVE_MAX_OUTPUT_TOKENS

enabled: false
base_url: http://127.0.0.1:50256/v1
model: your-openai-responses-model
api_key: sk-local
max_output_tokens: 16
# Documented intent only — the just recipe always uses --test-threads=1.
serial: true
"""

REQUIRED_FIELDS = ("enabled", "base_url", "model", "api_key", "max_output_tokens", "serial")


def main() -> int:
    TARGET.write_text(TEMPLATE)
    try:
        import yaml
    except ImportError:
        print(f"generated {TARGET.relative_to(REPO_ROOT)} (skip self-check: pyyaml missing)")
        return 0
    data = yaml.safe_load(TARGET.read_text())
    missing = [f for f in REQUIRED_FIELDS if f not in data]
    if missing:
        print(f"ERROR: generated example missing fields: {missing}", file=sys.stderr)
        return 1
    print(f"generated {TARGET.relative_to(REPO_ROOT)} (self-check ok)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
