#!/usr/bin/env python3
"""Generate src/app/tui/designing/generated/AGENT-INDEX.md from modules/.

Usage:
  python3 scripts/gen_designing_index.py
  python3 scripts/gen_designing_index.py --stdout
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MODULES = REPO / "src" / "app" / "tui" / "designing" / "modules"
INDEX = REPO / "src" / "app" / "tui" / "designing" / "generated" / "AGENT-INDEX.md"


def module_summary(intent: Path) -> str:
    for raw in intent.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith(">"):
            continue
        return line
    return ""


def render_index() -> str:
    rows: list[str] = []
    if MODULES.is_dir():
        for path in sorted(p for p in MODULES.iterdir() if p.is_dir()):
            intent = path / "intent.md"
            states_dir = path / "states"
            states = (
                sorted(p.stem for p in states_dir.glob("*.yaml"))
                if states_dir.is_dir()
                else []
            )
            summary = module_summary(intent) if intent.is_file() else "(missing intent.md)"
            rows.append(f"| {path.name} | {summary} | {', '.join(states) or '—'} |")
    body = "\n".join(rows) if rows else "| — | (no modules) | — |"
    return (
        "<!-- AUTO-GENERATED by scripts/gen_designing_index.py — do not edit. -->\n"
        "# designing AGENT-INDEX\n\n"
        "Agent 找路：每模块一行。改某表面时读 `modules/<id>/intent.md` + `states/*.yaml`。"
        "禁止把 `app/` 或整包 HTML 当默认上下文。\n\n"
        "| id | 一句话 | states |\n"
        "|---|---|---|\n"
        f"{body}\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print instead of write")
    args = ap.parse_args()
    text = render_index()
    if args.stdout:
        sys.stdout.write(text)
        return 0
    INDEX.parent.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(text, encoding="utf-8")
    print(f"wrote {INDEX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
