#!/usr/bin/env python3
"""Generate configs/example.yaml (maintenance, not in qa).

Edit the TEMPLATE in this script, then run:
  python3 scripts/gen_config_example.py
  just gen-config-example

The checked-in file is the generated artifact — do not hand-edit it
except via this template. Self-check: YAML must parse.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TARGET = REPO_ROOT / "configs" / "example.yaml"

TEMPLATE = """\
# xylitol example configuration
# Auto-generated by scripts/gen_config_example.py — edit the template there.
# Place as .xylitol/config.yaml in your project (shareable; no secrets),
# and/or at $XDG_CONFIG_HOME/xylitol/config.yaml (~/.config/xylitol/config.yaml).
# Secrets: copy .xylitol/secret.env.example → secret.env (gitignored);
# reference keys in YAML as "{{ secret.OPENAI_API_KEY }}".
# User home path: "{{ vars.home }}" (only vars.home; do not hardcode /home/…).
# config.local.yaml is not supported.
# Local tokenizer encode gate (c1420): only on|off; default off if omitted.
# Quote to avoid YAML 1.1 boolean aliases in some parsers.
token_estimate:
  local_tokenizer: "off"

# Optional shared tokenizer sources (many models can point at one).
# Download: HF_ENDPOINT=https://hf-mirror.com xylitol tokenizer download qwen --yes
tokenizers:
  qwen36:
    repo: Qwen/Qwen3.6-35B-A3B
    # file: tokenizer.json

models:
  # Uncomment default_model + at least one entry under models before first use
  # (avoids accidental live calls from a checked-in example).
  # DeepSeek flash is the recommended starter; thinking_levels must be explicit
  # (omit → only off). Switch-model default = last list item (max here).
  # Levels/context below aligned to models.dev api.json (2026-08); capability
  # fields not yet on ModelEntry stay as comments (deny_unknown_fields).
  # default_model: "deepseek-v4-flash"
  models: {}
    # deepseek-v4-flash:
    #   provider: openai
    #   model: deepseek-v4-flash
    #   base_url: https://api.deepseek.com
    #   api: openai-responses
    #   compat: deepseek
    #   api_key: "{{ secret.DEEPSEEK_API_KEY }}"
    #   thinking: true
    #   thinking_levels: [off, low, high, max]
    #   context_window: 1000000
    #   # placeholders: tool_call/attachment/structured_output/modalities/cost/max_output
    # deepseek-v4-flash-anthropic:
    #   provider: anthropic
    #   model: deepseek-v4-flash
    #   base_url: https://api.deepseek.com/anthropic
    #   api: anthropic-messages
    #   compat: deepseek
    #   api_key: "{{ secret.DEEPSEEK_API_KEY }}"
    #   thinking: true
    #   thinking_levels: [off, low, high, max]
    #   context_window: 1000000
    # OpenCode Zen free（Completions）；别名用 *-zen 后缀：
    # deepseek-v4-flash-free-zen:
    #   provider: openai
    #   model: deepseek-v4-flash-free
    #   base_url: https://opencode.ai/zen/v1
    #   api: openai-completions
    #   compat: deepseek
    #   api_key: "{{ secret.OPENCODE_ZEN_API_KEY }}"
    #   thinking: true
    #   thinking_levels: [off, low, high, max]
    #   context_window: 200000
    # Optional Anthropic (uncomment only if you intend to use it):
    # claude:
    #   provider: anthropic
    #   model: claude-sonnet-4-20250514
    #   api_key: "{{ secret.ANTHROPIC_API_KEY }}"
    # Inference id ≠ tokenizer repo — share via tokenizers.qwen36:
    # qwen:
    #   provider: openai
    #   model: Qwen3.6-35B-A3B/UD-Q5_K_XL-think-coding
    #   base_url: "http://127.0.0.1:8000/v1"
    #   api: openai-responses
    #   tokenizer: qwen36
    # Or inline HF repo: tokenizer: Qwen/Qwen3.6-35B-A3B
    # Or local file:     tokenizer: ./path/to/tokenizer.json
    # Or shared local:
    # tokenizers:
    #   local_qwen:
    #     path: /abs/or/./rel/tokenizer.json
    # … then tokenizer: local_qwen

execution:
  max_retries: 3
  # system_prompt: "Custom system prompt override"
  # model: "deepseek-v4-flash"  # override default per-execution

security:
  enabled: true
  permission:
    enabled: false
    backend: glob  # only delivered backend (app-level glob matching)
    filesystem:
      read_allowed: []   # non-empty = default-deny for unlisted paths
      write_allowed: []
      write_denied:
        - "**/.env"
        - "**/secrets/**"
    network:
      allowed_domains: []  # non-empty = default-deny for unlisted domains
      denied_domains: []
    process:
      allowed_paths: []

tools:
  allowlist: []
  blocklist: []
  max_results: 1000
  max_file_size: 10485760  # 10 MB
  max_dir_entries: 1000

hooks:
  pre_tool_call: []
  post_tool_call: []

# Feature-gated sections (require corresponding feature flag):

# planning:
#   max_steps: 10
#   reasoning_depth: 2

# session:
#   storage:
#     backend: file
#     path: ".xylitol/sessions"
#   # Optional ReAct turn cap: bootstrap installs should_stop_after_turn.
#   # Omit / null = open-end (no product default max_iterations).
#   max_turns: 200

# skills:
#   - name: "custom-skill"
#     path: "./skills/custom"

# mcp_servers:  # YAML list (not Cursor-style mcpServers object)
#   # stdio (prefer PATH command name; or "{{ vars.home }}/…" for home-relative)
#   - name: "my-server"
#     transport: stdio   # default
#     command: "npx"
#     args: ["-y", "@my/mcp-server"]
#     env:
#       PATH: "/usr/bin:/bin"
#   # streamable HTTP / SSE (+ optional headers; use secret.env + {{ secret.KEY }})
#   - name: "context7"
#     transport: sse
#     url: "https://mcp.context7.com/mcp"
#     headers:
#       CONTEXT7_API_KEY: "{{ secret.CONTEXT7_API_KEY }}"

# Optional remote traces (OTLP/HTTP → Langfuse / Collector).
# Code defaults (omit keys or leave commented):
#   exporter: none
#   protocol: http-json
#   observation_io: none          # no prompt / completion / turn preview payloads
#   tool_observation_io: none     # no tool args/results
#   export_timeout_secs: 60
# Turning exporter on WITHOUT raising the I/O gates still sends only structural
# metadata (session id, model name, span types, latency, usage when present,
# xylitol.obs.lane=llm on agent/LLM spans).
# For llm vs infra fan-out, point endpoint at a Collector; see
# configs/examples/otel-collector-lane.yaml (ops-optional).
# otel:
#   exporter: otlp-http   # or omit / none
#   # endpoint: "http://localhost:3000/api/public/otel"
#   # (or set LANGFUSE_BASE_URL in secret.env → …/api/public/otel)
#   environment: dev
#   service_name: xylitol
#   # export_timeout_secs: 60
#   # observation_io: truncated   # none | truncated | full  (default none)
#   # tool_observation_io: truncated
"""


def main() -> int:
    TARGET.write_text(TEMPLATE)
    try:
        import yaml
    except ImportError:
        print(f"generated {TARGET.relative_to(REPO_ROOT)} (skip self-check: pyyaml missing)")
        return 0
    data = yaml.safe_load(TARGET.read_text())
    if not isinstance(data, dict) or "models" not in data:
        print("ERROR: generated example missing top-level models", file=sys.stderr)
        return 1
    models = data["models"]
    if not isinstance(models, dict) or "models" not in models:
        print("ERROR: generated example missing models.models map", file=sys.stderr)
        return 1
    print(f"generated {TARGET.relative_to(REPO_ROOT)} (self-check ok)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
