#!/usr/bin/env bash
# Generate llmanspec/dag.gen.md from proposal.md frontmatter
# Usage: ./scripts/generate-llmanspec-changes-dag.sh
# Output: llmanspec/dag.gen.md (add to .gitignore)
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
changes_dir="llmanspec/changes"
output="llmanspec/dag.gen.md"

if [ ! -d "$changes_dir" ]; then
  echo "Error: $changes_dir not found" >&2
  exit 1
fi

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

# Parse frontmatter from each proposal.md: extract depends_on and blocks
for proposal in "$changes_dir"/*/proposal.md; do
  [ -f "$proposal" ] || continue
  dir=$(dirname "$proposal")
  change_id=$(basename "$dir")

  # Extract YAML frontmatter between --- markers
  awk '/^---$/{n++; next} n==1{print}' "$proposal" > "$tmp"

  depends=$(python3 -c "
import yaml, sys
try:
    d = yaml.safe_load(open('$tmp'))
    deps = d.get('depends_on', []) or []
    print(','.join(deps) if deps else '')
except: print('')
" 2>/dev/null)

  blocks=$(python3 -c "
import yaml, sys
try:
    d = yaml.safe_load(open('$tmp'))
    blks = d.get('blocks', []) or []
    print(','.join(blks) if blks else '')
except: print('')
" 2>/dev/null)

  # Extract description from first non-empty, non-heading line after frontmatter
  desc=$(awk 'BEGIN{s=0} /^---$/{s++; next} s>=2 && /^[^#]/ && NF{print; exit}' "$proposal" | head -c 120)

  echo "$change_id|$depends|$blocks|$desc"
done | sort -t'|' -k1,1 > "${tmp}.data"

# Generate markdown
cat > "$output" <<'HEADER'
<!-- AUTO-GENERATED by scripts/generate-llmanspec-changes-dag.sh — DO NOT EDIT -->
<!-- Run: ./scripts/generate-llmanspec-changes-dag.sh to regenerate -->

# Change Dependency DAG (generated)

## Dependency Table

| Change | Depends On | Blocks | Description |
|--------|------------|--------|-------------|
HEADER

while IFS='|' read -r change_id depends blocks desc; do
  dep_display="${depends:----}"
  blk_display="${blocks:----}"
  [ -z "$depends" ] && dep_display="—"
  [ -z "$blocks" ] && blk_display="—"
  # Format lists nicely
  echo "$dep_display" | grep -q ',' && dep_display=$(echo "$dep_display" | tr ',' ', ')
  echo "$blk_display" | grep -q ',' && blk_display=$(echo "$blk_display" | tr ',' ', ')
  printf "| %s | %s | %s | %s |\n" "$change_id" "$dep_display" "$blk_display" "$desc"
done < "${tmp}.data" >> "$output"

# Generate mermaid graph
cat >> "$output" <<'MERMAID_HEADER'

## Graph Visualization

```mermaid
graph LR
MERMAID_HEADER

while IFS='|' read -r change_id depends blocks desc; do
  if [ -n "$depends" ]; then
    IFS=',' read -ra deps <<< "$depends"
    for dep in "${deps[@]}"; do
      dep=$(echo "$dep" | xargs)
      [ -n "$dep" ] && printf '    %s --> %s\n' "$dep" "$change_id" >> "$output"
    done
  fi
done < "${tmp}.data"

echo '```' >> "$output"

echo "Generated: $output"
