// Generated by `just gen-protocol-ts`. DO NOT EDIT.
// Product envelope + method-table payloads. OpenAPI is not the type SSOT.

// This file has been generated by Specta. Do not edit this file manually.
/**  Downlink payload for `approval/requested` (stable `rpcId` on the envelope). */
export type ApprovalRequestedPayload = {
	call_id: string,
};

/**  A command from the client. Each carries an optional `id` for correlation. */
export type Command = { type: "prompt"; id?: string | null; message: string } | { type: "abort"; id?: string | null } | { type: "get_state"; id?: string | null } | { type: "set_model"; id?: string | null; provider: string; model_id: string } | { type: "cycle_model"; id?: string | null } | { type: "get_available_models"; id?: string | null } | { type: "set_thinking_level"; id?: string | null; level: string } | { type: "bash"; id?: string | null; command: string; exclude_from_context?: boolean } | { type: "compact"; id?: string | null;
/**  Optional focus text for summarization (c1670; pi `customInstructions`). */
instructions?: string | null } | { type: "get_session_stats"; id?: string | null } | { type: "export_html"; id?: string | null; output_path?: string | null } | { type: "export_jsonl"; id?: string | null; output_path?: string | null } | { type: "import_jsonl"; id?: string | null; input_path: string } | { type: "switch_session"; id?: string | null; session_path: string } | { type: "fork"; id?: string | null; entry_id: string;
/**  `"before"` | `"at"` (default `"at"`). */
position?: string | null } | { type: "get_messages"; id?: string | null } | { type: "get_commands"; id?: string | null } | { type: "steer"; id?: string | null; message: string } | { type: "follow_up"; id?: string | null; message: string } | { type: "clear_queue"; id?: string | null; clear_steer?: boolean; clear_follow_up?: boolean } |
/**  Subscribe to a session's event stream (WebSocket). */
{ type: "subscribe"; id?: string | null; session_id: string; last_seq: number } |
/**  Approve a tool execution (reverse RPC response). */
{ type: "approve_tool"; id?: string | null; call_id: string; approved: boolean } |
/**  Answer a user question (reverse RPC response). */
{ type: "answer_question"; id?: string | null; call_id: string; answer: string } | { type: "quit"; id?: string | null };

/**
 *  An event from the core: either a response to a command or a streamed
 *  occurrence during a turn.
 */
export type Event = { type: "error"; id?: string | null; kind?: string | null; message: string } | { type: "response"; id?: string | null; payload?: any } | { type: "text_delta"; text: string } |
/**  Streaming thinking / reasoning text (e.g. Anthropic extended thinking). */
{ type: "thinking_delta"; text: string } | { type: "tool_start"; id: string; name: string } | { type: "tool_end"; id: string; name: string; result: string } | { type: "agent_end" } | { type: "model_select"; provider: string; model_id: string } | { type: "compaction_start"; reason: string } |
/**  Acknowledgment of a Subscribe command. */
{ type: "subscribed"; session_id: string; seq: number } | { type: "bash_result"; id?: string | null; output: string; exit_code: number | null; cancelled: boolean; truncated: boolean } |
/**  Turn started. */
{ type: "turn_start"; turn_index: number } |
/**  Turn ended. */
{ type: "turn_end"; turn_index: number } |
/**  Message started. */
{ type: "message_start"; role: string } |
/**  Message ended. */
{ type: "message_end"; role: string } |
/**  Streaming message update (replaces previous text/thinking for this message). */
{ type: "message_update"; text: string; thinking?: string | null } |
/**  Streaming tool execution output. */
{ type: "tool_execution_update"; id: string; output: string } |
/**  Compaction completed. */
{ type: "compaction_end" } |
/**  Shared context-token settlement (c1860) for footer / cross-client chrome. */
{ type: "context_token_settlement"; tokens: number; provenance: string; usage_tokens: number; trailing_tokens: number; last_usage_index?: number | null; reason: string; generation: number } |
/**  Pending steer / follow-up queue depths (cross-client badge). */
{ type: "queue_update"; steer_count: number; follow_up_count: number };

/**  `host.describe` result.value. */
export type HostDescribeValue = {
	protocol: number,
};

/**  Downlink payload for `host/hello`. */
export type HostHelloPayload = {
	protocol: number,
};

/**  Downlink payload for `question/requested` (stable `rpcId` on the envelope). */
export type QuestionRequestedPayload = {
	call_id: string,
};

export type RpcError = {
	code: string,
	details: string,
};

/**  Discriminated four-quadrant message. */
export type RpcMessage = { type: "client-request"; rpcId: string; method: string; payload?: any } | { type: "server-response"; rpcId: string; result: RpcResult } | { type: "server-request"; rpcId: string; method: string; payload?: any } | { type: "client-response"; rpcId: string; payload?: any };

/**  Unary / respond result. HTTP 200 means the envelope parsed. */
export type RpcResult = {
	ok: boolean,
	value?: any | null,
	error?: RpcError | null,
};

/**  Downlink payload for `session/event`. */
export type SessionEventPayload = {
	session_id: string,
	seq: number,
	event: Event,
};

/**  Downlink payload for `session/resync_required`. */
export type SessionResyncRequiredPayload = {
	session_id: string,
};

/**  Downlink payload for `session/subscribed`. */
export type SessionSubscribedPayload = {
	session_id: string,
	seq: number,
};

export const PROTOCOL_VERSION = 1 as const;
export const UNARY_METHODS = [
  "prompt",
  "abort",
  "get_state",
  "set_model",
  "cycle_model",
  "get_available_models",
  "set_thinking_level",
  "bash",
  "compact",
  "get_session_stats",
  "export_html",
  "export_jsonl",
  "import_jsonl",
  "switch_session",
  "fork",
  "get_messages",
  "get_commands",
  "steer",
  "follow_up",
  "clear_queue",
  "subscribe",
  "host.describe",
] as const;
export type UnaryMethod = typeof UNARY_METHODS[number];
export const DOWNLINK_METHODS = [
  "session/event",
  "session/subscribed",
  "session/resync_required",
  "approval/requested",
  "question/requested",
  "host/hello",
] as const;
export type DownlinkMethod = typeof DOWNLINK_METHODS[number];
