# language: zh-CN
# generated by `llman sdd solidify` from spec.toon (domain-security)
功能: domain-security
  场景: network-domain-block
    假如 blocked_domains 含 evil.com
    当 检查网络域名 evil.com
    那么 结果应为拒绝
