# language: zh-CN
# generated by `llman sdd solidify` from spec.toon (domain-security)
# executable permission subset (migrated from tests/features/sandbox.feature)
功能: domain-security
  场景: network-domain-block
    假如 沙箱引擎已初始化
    当 检查网络域名 "evil.com"
    那么 结果应为拒绝且原因含 denied_domains

  场景: deny-write
    假如 沙箱引擎已初始化
    当 检查写入路径 "/project/.env"
    那么 结果应为拒绝且原因含 write_denied

  场景: allow-write
    假如 沙箱引擎已初始化
    当 检查写入路径 "/project/src/main.rs"
    那么 结果应为允许
